"""Protocols and shared types for bot radio backends."""

from __future__ import annotations

from collections.abc import Awaitable, Callable
from dataclasses import dataclass
from typing import Any, Protocol

from .events import BackendEvent, BackendEventType

BackendCallback = Callable[[BackendEvent, dict[str, Any] | None], Awaitable[None] | None]


@dataclass(frozen=True)
class BackendCapabilities:
    """Feature flags used to keep backend-specific behavior explicit."""

    backend_name: str
    unlimited_contacts: bool = False
    supports_cli_fallback: bool = False
    supports_device_contacts: bool = True
    supports_channel_config: bool = True
    supports_trace: bool = False
    supports_telemetry: bool = False
    supports_radio_config: bool = False
    supports_reboot: bool = False
    supports_custom_vars: bool = False
    supports_time: bool = True


class RadioCommands(Protocol):
    """Command surface used by existing bot modules."""

    async def get_contacts(self) -> Any: ...
    async def send_msg(self, contact: dict[str, Any], content: str) -> Any: ...
    async def send_msg_with_retry(self, contact: dict[str, Any], content: str, **kwargs: Any) -> Any: ...
    async def send_chan_msg(self, channel_idx: int, content: str, timestamp: int | None = None) -> Any: ...
    async def send_advert(self, flood: bool = False) -> Any: ...
    async def get_channel(self, channel_idx: int) -> Any: ...
    async def set_channel(self, channel_idx: int, name: str, secret: bytes | str | None = None) -> Any: ...
    async def set_flood_scope(self, scope: str) -> Any: ...
    async def get_time(self) -> Any: ...
    async def set_time(self, timestamp: int) -> Any: ...
    async def set_name(self, name: str) -> Any: ...
    async def reboot(self) -> Any: ...
    async def send_device_query(self) -> Any: ...
    async def add_contact(self, *args: Any, **kwargs: Any) -> Any: ...
    async def remove_contact(self, public_key: str) -> Any: ...
    async def change_contact_flags(self, contact: dict[str, Any], flags: int) -> Any: ...
    async def set_manual_add_contacts(self, enabled: bool) -> Any: ...
    async def set_autoadd_config(self, value: int) -> Any: ...


class RadioBackend(Protocol):
    """Backend-neutral radio object exposed as `bot.radio_backend`."""

    commands: RadioCommands
    contacts: dict[str, dict[str, Any]]
    channels: dict[int, dict[str, Any]]
    self_info: dict[str, Any]
    capabilities: BackendCapabilities

    @property
    def is_connected(self) -> bool: ...
    async def connect(self) -> bool: ...
    async def disconnect(self) -> None: ...
    async def start_auto_message_fetching(self) -> None: ...
    def subscribe(self, event_type: BackendEventType, callback: BackendCallback) -> Any: ...
    def get_contact_by_name(self, name: str) -> dict[str, Any] | None: ...
    def get_contact_by_key_prefix(self, prefix: str) -> dict[str, Any] | None: ...
    async def wait_for_event(
        self,
        event_type: BackendEventType,
        attribute_filters: dict[str, Any] | None = None,
        timeout: float = 10.0,
    ) -> BackendEvent | None: ...
    async def health_check(self) -> bool: ...
